### PR TITLE
TypeScript Codegen - Autogenerated Header

### PR DESCRIPTION
**Pull request by solomonhawk**
Hello,

I hope it's ok to send over this small proposed change. I found myself wishing the generated types file contained a header marking it as machine-generated.

~The other change here might be more controversial. I'm not sure how particular it is to the tooling I'm accustomed to and it seems fraught for the GrowthBook CLI to try to satisfy all parties with the formatting of the generated file. In my case, Prettier/ESLint was catching and fixing the generated type file to remove unnecessary quotes around keys. I figured we could try to generate non-quoted keys where it is safe to do so and fall back to quoted keys if necessary.~

~It's not a big deal - but I think it's quite popular to avoid quoted keys unless necessary.~

Open to your feedback!

### CODE REVIEW

**Comment by tinahollygb** [comment]
Thanks for your contribution. 

The header change makes sense. Can you link only to the top-level "Generating Types" on that page? I just realized there's 2 and the 2nd one has a `-1` suffix which is not ideal. We will probably change that.

I don't think the quote change makes sense as different ESLint and Prettier configurations will use different quote styles, for example, the main GrowthBook project uses double quotes so we'll still need to have our formatter run over it and make changes, and [we do that anyways](https://github.com/growthbook/growthbook/blob/main/packages/front-end/types/app-features.ts). If we went with double quotes as the preferred style, you'd still need to do this. I'd prefer to not include that change especially with the added complexity.

**Comment by solomonhawk** [comment]
@tinahollygb That makes sense and is honestly what I expected to hear. I've removed the formatting change and fixed up the URL. Appreciate the quick review 🙏

**Comment by tinahollygb** [comment]
Thanks @solomonhawk 🚀

**Comment by solomonhawk** [comment]
@tinahollygb Is there an upcoming release scheduled that might include this change?

**Comment by tinahollygb** [comment]
@solomonhawk I just published it now, it should be available, thanks for the reminder.

**Comment by solomonhawk** [comment]
Thanks a bunch 🎉

**Pull request merged**
